import { getASSStyleFromConfig } from './captionConfig.js';

/**
 * Formats a duration in seconds to the standard ASS timestamp format: H:MM:SS.cs
 * e.g., 0:02:14.35 (where cs is centiseconds, 1cs = 10ms)
 * 
 * @param {number} seconds - The time in seconds.
 * @returns {string} The formatted timestamp.
 */
export function formatASSTimestamp(seconds) {
  if (typeof seconds !== 'number' || isNaN(seconds) || seconds < 0) {
    seconds = 0;
  }
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  
  // Calculate centiseconds (.00 to .99)
  const cs = Math.round((seconds - Math.floor(seconds)) * 100);

  const formattedHrs = hrs.toString();
  const formattedMins = mins.toString().padStart(2, '0');
  const formattedSecs = secs.toString().padStart(2, '0');
  const formattedCs = Math.min(99, Math.max(0, cs)).toString().padStart(2, '0');

  return `${formattedHrs}:${formattedMins}:${formattedSecs}.${formattedCs}`;
}

/**
 * Builds the ASS format string header with metadata and styles configured for short form video.
 * 
 * @param {object} styles - The resolved style preferences.
 * @returns {string} The formatted file header sections.
 */
export function generateASSHeader(styles = {}) {
  const fontName = styles.fontName || 'Montserrat SemiBold';
  const fontSize = styles.fontSize || 72;
  const primaryColor = styles.primaryColor || '&H0000FFFF';
  const secondaryColor = styles.secondaryColor || '&H00FFFFFF';
  const outlineColor = styles.outlineColor || '&H00000000';
  const backColor = styles.backColor || '&H00000000';
  const bold = styles.bold !== undefined ? styles.bold : -1;
  const outlineSize = styles.outlineSize !== undefined ? styles.outlineSize : 5;
  const shadowSize = styles.shadowSize !== undefined ? styles.shadowSize : 0;
  const alignment = styles.alignment || 2;
  const marginV = styles.marginV !== undefined ? styles.marginV : 300;
  const borderStyle = styles.borderStyle !== undefined ? styles.borderStyle : 1;

  return [
    '[Script Info]',
    '; Script generated by Caption Studio',
    'Title: Caption Studio Subtitles',
    'ScriptType: v4.00+',
    'WrapStyle: 0',
    'PlayResX: 1080',
    'PlayResY: 1920', // Configured for vertical 9:16 environments
    'ScaledBorderAndShadow: yes',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    `Style: Default,${fontName},${fontSize},${primaryColor},${secondaryColor},${outlineColor},${backColor},${bold},0,0,0,100,100,0,0,${borderStyle},${outlineSize},${shadowSize},${alignment},100,100,${marginV},1`,
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'
  ].join('\n');
}

/**
 * Converts a phrase object containing word units into a dialogue entry with karaoke (\kf) tags.
 * 
 * @param {object} phrase - Unified phrase containing start, end, text, and words array.
 * @param {string} textCase - The case output mode ('uppercase' or 'normal').
 * @returns {string} The ASS Dialogue Event line.
 */
export function generateASSDialogueLine(phrase, textCase = 'uppercase') {
  const startStr = formatASSTimestamp(phrase.start);
  const endStr = formatASSTimestamp(phrase.end);
  
  let textPayload = '';
  let lastTime = phrase.start;

  phrase.words.forEach((w, idx) => {
    // Determine pause before the word (in centiseconds)
    const delay = Math.max(0, Math.round((w.start - lastTime) * 100));
    // Determine word duration in centiseconds
    const duration = Math.max(1, Math.round((w.end - w.start) * 100));

    // Append pause tag if there is a gap between word events
    if (delay > 0) {
      textPayload += `{\\kf${delay}}`;
    }

    let wordText = (w.word || w.text || '').trim();
    if (textCase === 'uppercase') {
      wordText = wordText.toUpperCase();
    }

    // Add space before this word if it is not the first word
    if (idx > 0) {
      textPayload += ` {\\kf${duration}}${wordText}`;
    } else {
      textPayload += `{\\kf${duration}}${wordText}`;
    }
    
    lastTime = w.end;
  });

  return `Dialogue: 0,${startStr},${endStr},Default,,0,0,0,,${textPayload}`;
}

/**
 * Helper to translate frontend styles choices into raw ASS style configurations.
 * Delegated to the shared single source of truth captionConfig schema.
 * 
 * @param {object} params - Input style settings from the client.
 * @returns {object} The resolved ASS Style parameters.
 */
export function resolveASSStyle(params = {}) {
  return getASSStyleFromConfig(params);
}
