/**
 * Formats a duration in seconds to the standard ASS timestamp format: H:MM:SS.cs
 * e.g., 0:02:14.35 (where cs is centiseconds, 1cs = 10ms)
 * 
 * @param {number} seconds - The time in seconds.
 * @returns {string} The formatted timestamp.
 */
export function formatASSTimestamp(seconds) {
  if (typeof seconds !== 'number' || isNaN(seconds) || seconds < 0) {
    seconds = 0;
  }
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  
  // Calculate centiseconds (.00 to .99)
  const cs = Math.round((seconds - Math.floor(seconds)) * 100);

  const formattedHrs = hrs.toString();
  const formattedMins = mins.toString().padStart(2, '0');
  const formattedSecs = secs.toString().padStart(2, '0');
  const formattedCs = Math.min(99, Math.max(0, cs)).toString().padStart(2, '0');

  return `${formattedHrs}:${formattedMins}:${formattedSecs}.${formattedCs}`;
}

/**
 * Builds the ASS format string header with metadata and styles configured for short form video.
 * 
 * @returns {string} The formatted file header sections.
 */
export function generateASSHeader() {
  return [
    '[Script Info]',
    '; Script generated by Caption Studio',
    'Title: Caption Studio Subtitles',
    'ScriptType: v4.00+',
    'WrapStyle: 0',
    'PlayResX: 1080',
    'PlayResY: 1920', // Configured for vertical 9:16 environments
    'ScaledBorderAndShadow: yes',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    // Default Style parameters:
    // Montserrat SemiBold, Size 72, Primary: White (&H00FFFFFF), Secondary: Yellow (&H0000FFFF), Outline: Black (&H00000000)
    // ScaleX/Y = 100%, Bold, Outline=5, Shadow=0, Alignment=2 (Bottom Center), MarginV=300 (Mobile safe vertical margin)
    'Style: Default,Montserrat SemiBold,72,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,5,0,2,100,100,300,1',
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'
  ].join('\n');
}

/**
 * Converts a phrase object containing word units into a dialogue entry with karaoke (\k) tags.
 * Handles spacing and centisecond durations properly.
 * 
 * @param {object} phrase - Unified phrase containing start, end, text, and words array.
 * @returns {string} The ASS Dialogue Event line.
 */
export function generateASSDialogueLine(phrase) {
  const startStr = formatASSTimestamp(phrase.start);
  const endStr = formatASSTimestamp(phrase.end);
  
  let textPayload = '';
  let lastTime = phrase.start;

  phrase.words.forEach((w, idx) => {
    // Determine pause before the word
    const delay = Math.max(0, Math.round((w.start - lastTime) * 100));
    // Determine word duration in centiseconds
    const duration = Math.max(1, Math.round((w.end - w.start) * 100));

    // Append pause tag if there is a gap between word events
    if (delay > 0) {
      textPayload += `{\\k${delay}}`;
    }

    // Capture spacing format returned by Whisper. Convert spaces or append space.
    // If it contains trailing or leading spaces, incorporate them.
    const wordText = w.text;
    textPayload += `{\\k${duration}}${wordText}`;
    
    lastTime = w.end;
  });

  // Balanced line breaking algorithm if character count is high (>25)
  // Max 2 lines. Words are never split.
  const rawTextContent = phrase.words.map(w => w.text.trim()).join(' ');
  
  if (rawTextContent.length > 25) {
    // If we have a line break inside, we have to preserve the karaoke tags or insert a \N newline.
    // Let's identify the middle-most word index to split the lines balanced.
    const midIndex = Math.floor(phrase.words.length / 2);
    if (midIndex > 0 && midIndex < phrase.words.length) {
      let segmentText = '';
      let breakTime = phrase.start;
      
      const firstHalf = phrase.words.slice(0, midIndex);
      const secondHalf = phrase.words.slice(midIndex);

      let text1 = '';
      firstHalf.forEach(w => {
        const delay = Math.max(0, Math.round((w.start - breakTime) * 100));
        const duration = Math.max(1, Math.round((w.end - w.start) * 100));
        if (delay > 0) text1 += `{\\k${delay}}`;
        text1 += `{\\k${duration}}${w.text}`;
        breakTime = w.end;
      });

      let text2 = '';
      secondHalf.forEach(w => {
        const delay = Math.max(0, Math.round((w.start - breakTime) * 100));
        const duration = Math.max(1, Math.round((w.end - w.start) * 100));
        if (delay > 0) text2 += `{\\k${delay}}`;
        text2 += `{\\k${duration}}${w.text}`;
        breakTime = w.end;
      });

      // Combine with \N override character for line breaking
      textPayload = `${text1.trim()}\\N${text2.trim()}`;
    }
  }

  return `Dialogue: 0,${startStr},${endStr},Default,,0,0,0,,${textPayload}`;
}
