/**
 * THE BHYND SOUND PACK — a designed, coherent library of editing sounds,
 * generated by backend/scripts/generate-sound-pack.js.
 *
 * WHY A PACK, not more sounds in the registry. The library this sits beside
 * grew by accretion: synthesized placeholders, then whatever sounds were to
 * hand. Measured, it spans 32 dB of loudness (a whoosh at -39 LUFS next to a
 * violin at -7), several files start with up to 1.6 s of silence (a sound
 * placed on a word plays late by exactly that), and many clip. A pack is the
 * opposite: every sound in it was made for this editor, by one generator, to
 * one set of rules —
 *
 *   - it STARTS on its first sample, so word-level placement is exact;
 *   - it is mastered to its family's level UNDER SPEECH (see targetLufsM),
 *     measured against real short-form dialogue (the home-office test video
 *     integrates at -16.5 LUFS), so placing one never jumps out;
 *   - it peaks at -1 dBTP or lower, so a run of them stacked on speech has
 *     headroom before the export's limiter has to act;
 *   - its low end is built to survive a PHONE speaker (see the generator), so
 *     an impact is not silently lost on the device most viewers use.
 *
 * WHERE THINGS LIVE. This file holds the pack's STRUCTURE — sections,
 * families, tiers, and the rules for levels and usage — which is hand-written.
 * The per-sound entries are authored beside their recipes in
 * backend/scripts/sound-pack/recipes/ and written, with each file's MEASURED
 * duration and level, into ./soundPackManifest.js by the generator. So a
 * sound's name and its audio are authored in one place, and its duration can
 * never be typed wrong.
 */
import { PACK_MANIFEST } from './soundPackManifest.js';

export const PACK_ID = 'bhynd';

/**
 * Every pack sound is placed at this clip volume by default, and each file is
 * mastered so that AT this volume it reaches its family's target. 70% rather
 * than 100%: it matches the default most of the existing library already
 * uses, so swapping a classic sound for a pack sound with Replace (which keeps
 * the clip's volume) lands at roughly the right level, and it leaves ~9 dB of
 * upward room on the 0-200% volume control.
 */
export const PACK_DEFAULT_VOLUME = 0.7;

/** How the AI Editorial system may use a sound. */
export const USAGE_WORD = 'word';     // short, dry, tail-free: safe on consecutive words
export const USAGE_MOMENT = 'moment'; // weight, movement or a tail: for the few beats that deserve one

/**
 * The hierarchy, from sounds you place on every other word to sounds you use
 * once a video. MICRO sounds are the only ones the AI will put on runs of
 * words; everything else is a moment.
 */
export const PACK_TIERS = [
  { id: 'micro', label: 'Micro', usage: USAGE_WORD, note: 'Frequent, word-level. Dry, tail-free, repeatable.' },
  { id: 'subtle', label: 'Subtle', usage: USAGE_MOMENT, note: 'Sits under speech without being noticed as a sound.' },
  { id: 'medium', label: 'Medium', usage: USAGE_MOMENT, note: 'A noticeable editorial accent.' },
  { id: 'strong', label: 'Strong', usage: USAGE_MOMENT, note: 'Important moments.' },
  { id: 'cinematic', label: 'Cinematic', usage: USAGE_MOMENT, note: 'Occasional, dramatic.' },
  { id: 'comedic', label: 'Comedic', usage: USAGE_MOMENT, note: 'A specific editorial choice, used sparingly.' }
];

/** The picker's top-level grouping, in order. */
export const PACK_SECTIONS = [
  { id: 'text', label: 'Text & Captions' },
  { id: 'cinematic', label: 'Cinematic & Impact' },
  { id: 'ui', label: 'UI & Digital' },
  { id: 'tech', label: 'Tech, Electric & Glitch' },
  { id: 'motion', label: 'Motion & Transitions' },
  { id: 'mood', label: 'Mood & Reaction' },
  { id: 'foley', label: 'Foley' }
];

/**
 * Families, in picker order within their section. `targetLufsM` is the
 * family's momentary loudness (EBU R128, 400 ms) at PACK_DEFAULT_VOLUME: an
 * offset below speech chosen per family — word-level sounds about 10 dB under
 * dialogue because they repeat, impacts about 5 dB under because they are
 * rare and meant to be felt, shimmer and air lowest of all because their job
 * is to be felt rather than heard. A sound may carry its own `gain` offset on
 * top, which is how "soft" and "hard" versions within a family differ.
 */
export const PACK_FAMILIES = [
  { id: 'micro', label: 'Micro', section: 'text', targetLufsM: -27.5 },
  { id: 'pop', label: 'Pop', section: 'text', targetLufsM: -25.5 },
  { id: 'pluck', label: 'Pluck', section: 'text', targetLufsM: -26.5 },
  { id: 'blip', label: 'Blip', section: 'text', targetLufsM: -27 },
  { id: 'caption', label: 'Caption Accents', section: 'text', targetLufsM: -26.5 },

  { id: 'cinematic', label: 'Cinematic', section: 'cinematic', targetLufsM: -22.5 },
  { id: 'sting', label: 'Sting', section: 'cinematic', targetLufsM: -23 },
  { id: 'impact', label: 'Impact', section: 'cinematic', targetLufsM: -22.5 },
  { id: 'drop', label: 'Drop', section: 'cinematic', targetLufsM: -23.5 },
  { id: 'low', label: 'Low End', section: 'cinematic', targetLufsM: -25 },

  { id: 'ui', label: 'Interface', section: 'ui', targetLufsM: -27.5 },
  { id: 'digital', label: 'Digital', section: 'ui', targetLufsM: -26.5 },
  { id: 'success', label: 'Success & Reward', section: 'ui', targetLufsM: -25 },

  { id: 'scifi', label: 'Sci-Fi & AI', section: 'tech', targetLufsM: -25.5 },
  { id: 'electric', label: 'Electric & Light', section: 'tech', targetLufsM: -25.5 },
  { id: 'glitch', label: 'Glitch', section: 'tech', targetLufsM: -26.5 },

  { id: 'whoosh', label: 'Whoosh', section: 'motion', targetLufsM: -25.5 },
  { id: 'motion', label: 'Movement', section: 'motion', targetLufsM: -26 },
  { id: 'transition', label: 'Transition', section: 'motion', targetLufsM: -24 },
  { id: 'rise', label: 'Rise & Reverse', section: 'motion', targetLufsM: -24.5 },
  { id: 'air', label: 'Air', section: 'motion', targetLufsM: -28.5 },

  { id: 'chime', label: 'Chime', section: 'mood', targetLufsM: -25.5 },
  { id: 'shimmer', label: 'Shimmer & Sparkle', section: 'mood', targetLufsM: -30.5 },
  { id: 'tension', label: 'Tension', section: 'mood', targetLufsM: -25 },
  { id: 'comedy', label: 'Comedy', section: 'mood', targetLufsM: -23.5 },

  { id: 'writing', label: 'Writing & Drawing', section: 'foley', targetLufsM: -27 },
  { id: 'paper', label: 'Paper', section: 'foley', targetLufsM: -26.5 },
  { id: 'device', label: 'Keyboard, Mouse & Phone', section: 'foley', targetLufsM: -27 },
  { id: 'object', label: 'Objects', section: 'foley', targetLufsM: -26 },
  { id: 'camera', label: 'Camera & Video', section: 'foley', targetLufsM: -26 },
  { id: 'stop', label: 'Stop & Interrupt', section: 'foley', targetLufsM: -24 }
];

/** Tier -> usage, unless a sound states its own (a soft chime can be word-safe). */
export function usageFor(sound) {
  return sound.usage || PACK_TIERS.find((t) => t.id === sound.tier)?.usage || USAGE_MOMENT;
}

/**
 * Every pack sound, from the generated manifest: `{ id, label, family, tier,
 * usage, tags, use, literal, duration, channels, lufsM, truePeak }`.
 */
export const PACK_SOUNDS = PACK_MANIFEST;

/** The pack file for a sound id — `bh-` keeps the pack grouped and collision-free on disk. */
export function packFileName(id) {
  return `bh-${id}.wav`;
}
